### ISSUE TITLE
[Feature request] Print output as json when using CLI (instead of creating file)

### ISSUE THREAD

**Issue by vesper8** [drawrowfly/amazon-scraper#13]
Hi there, first of all thanks a lot for making this, it's very well made and extremely useful. I'm going to be creating a few feature requests if you don't mind.

The first is that I would prefer if I could pass an argument on the CLI so that the return value is printed out instead of having a file created. This is because this CLI call is being called programatically from a PHP script and it makes it much easier to store the output inside a database then having to have a file created, figure out the filename, then read the file's content and store that in a database, and then delete the file

I imagine adding a new flag such as --output cli / file (default file) would be very simple

Thank you!

**Comment by drawrowfly** [comment]
Hello,

Ok, i think it will be useful

**Comment by drawrowfly** [comment]
--filetype '' and data will be displayed in the terminal in Raw format
