### ISSUE TITLE
[Feature request] Indicate currency in the price section

### ISSUE THREAD

**Issue by vesper8** [drawrowfly/amazon-scraper#16]
This is a minor one but it would be nice if based on the host, the currency could also be indicated in the returned json inside the `price` array. So .com -> USD, .co.uk -> GBP, etc

Of course we can do this on our end but it would be a nice extra if it was handled at the source

Many thanks!!

**Comment by drawrowfly** [comment]
Will be added to the todo list

**Comment by drawrowfly** [comment]
It is available on the latest updated
