### ISSUE TITLE
[Feature request] Add location or pincode filter (in options)

### ISSUE THREAD

**Issue by 20226012** [drawrowfly/amazon-scraper#17]
Currently the module doesn't support location based search.

It has been observed the results are different based on location
Location X -> Results are different / price etc.
Location Y -> Results are different / price etc.

**Comment by drawrowfly** [comment]
you can set custom host, if that is what you are asking for

**Comment by 20226012** [comment]
@drawrowfly , custom host gives the country level data but within a country we have multiple states and city level segregation (selection you address). Prices are different for product across states/cities/pin code, also serviceability of products is blocked to some pin codes

![Screen Shot 2020-08-17 at 1 09 48 PM](https://user-images.githubusercontent.com/10459966/90370426-03613680-e08b-11ea-99b0-a68e1fc585d1.png)

**Comment by drawrowfly** [comment]
address it self is binded to the session. this can be done actually pretty easy, just need to store the session in file for example
