### ISSUE TITLE
problem with special caracter in title

### ISSUE THREAD

**Issue by jeebee2013** [drawrowfly/amazon-scraper#6]
Hi drawrowfly
thanks for your work 
Seems to have a problem when title include special caracter (for example French letter : é, è, à )
in that case script is wainting for response and get stuck.
some exemple asin:
B07GVY1WXF
B07TJG7H5M

thanks

**Comment by drawrowfly** [comment]
Hi,

I will take a look at it soon and update the repo

**Comment by drawrowfly** [comment]
Made few tests works great with any character
